set shell := ["bash", "-eo", "pipefail", "-c"]

version := env_var_or_default("VERSION", "0.1.0")
commit := env_var_or_default("COMMIT", `git rev-parse --short=12 HEAD 2>/dev/null || echo unknown`)
out_dir := env_var_or_default("OUT_DIR", "dist")

default:
    @just --list

verify:
    #!/usr/bin/env bash
    set -euo pipefail
    umask 0022
    go mod verify
    go test ./...
    go test -race ./...
    go vet ./...

# Download the current official PingCode API description and prove that the
# loader can convert the complete corpus.
pingcode-spec-check:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    spec_file="$(mktemp "$(cd "{{ out_dir }}" && pwd)/pingcode-api-data.XXXXXX.json")"
    trap 'rm "$spec_file"' EXIT
    curl --fail --silent --show-error --location \
      https://open.pingcode.com/api_data.json \
      --output "$spec_file"
    PINGCODE_API_DATA_FILE="$spec_file" \
      go test -run TestOfficialAPIDocFile -v ./internal/pingcodert

# Download the pinned default FNS Swagger description and prove conversion,
# filtering, and Restish command generation against it.
fns-spec-check:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    spec_file="$(mktemp "$(cd "{{ out_dir }}" && pwd)/fns-swagger.XXXXXX.yaml")"
    trap 'rm "$spec_file"' EXIT
    curl --fail --silent --show-error --location \
      https://raw.githubusercontent.com/haierkeys/fast-note-sync-service/3.5.1/docs/swagger.yaml \
      --output "$spec_file"
    FNS_SPEC_CHECK_FILE="$spec_file" \
      go test -run TestPinnedSpecFile -v ./internal/fnsrt

# Refresh and verify third-party compliance evidence for release binaries.
compliance-check:
    #!/usr/bin/env bash
    set -euo pipefail
    umask 0022
    {
      echo "# Linked module closure for release binaries"
      echo "# Generated by: just compliance-check"
      echo "# Scope: union of go list -deps for ./cmd/aicli ./cmd/pingcode ./cmd/fns"
      echo
      for pkg in ./cmd/aicli ./cmd/pingcode ./cmd/fns; do
        echo "## $pkg"
        go list -deps -json "$pkg" | jq -r 'select((.Standard|not) and .Module != null) | [.Module.Path, .Module.Version] | @tsv' | sort -u
        echo
      done
      echo "## union"
      for pkg in ./cmd/aicli ./cmd/pingcode ./cmd/fns; do
        go list -deps -json "$pkg" | jq -r 'select((.Standard|not) and .Module != null) | [.Module.Path, .Module.Version] | @tsv'
      done | sort -u
    } > openwiki/compliance/modules-linked.txt
    go mod verify | tee openwiki/compliance/go-mod-verify.txt
    set +e
    if command -v govulncheck >/dev/null 2>&1; then
      govulncheck ./... >openwiki/compliance/govulncheck.txt 2>&1
    else
      go run golang.org/x/vuln/cmd/govulncheck@latest ./... >openwiki/compliance/govulncheck.txt 2>&1
    fi
    status=$?
    cat openwiki/compliance/govulncheck.txt
    set -e
    # govulncheck exits 3 when findings exist; `go run` may wrap that as 1.
    if [[ "$status" -eq 0 || "$status" -eq 3 ]]; then
      exit 0
    fi
    if grep -q 'GO-2026-4740' openwiki/compliance/govulncheck.txt; then
      exit 0
    fi
    exit "$status"

test:
    go test ./...

test-fns:
    go test ./internal/swagger2rt ./internal/fnsrt ./cmd/fns

build-fns: _validate-version
    @just _build-fns linux amd64
    @just _build-fns linux arm64

verify-fns: test-fns
    @just build-fns

build-pingcode: _validate-version
    @just _build-pingcode linux amd64
    @just _build-pingcode linux arm64

build: build-pingcode build-fns

release-build: _validate-version
    @just build-archive aicli linux amd64
    @just build-archive aicli linux arm64
    @just build-archive aicli darwin amd64
    @just build-archive aicli darwin arm64
    @just build-archive aicli windows amd64
    @just build-archive aicli windows arm64
    @just build-archive pingcode linux amd64
    @just build-archive pingcode linux arm64
    @just build-archive pingcode darwin amd64
    @just build-archive pingcode darwin arm64
    @just build-archive pingcode windows amd64
    @just build-archive pingcode windows arm64
    @just build-archive fns linux amd64
    @just build-archive fns linux arm64
    @just build-archive fns darwin amd64
    @just build-archive fns darwin arm64
    @just build-archive fns windows amd64
    @just build-archive fns windows arm64
    @just release-checksums
    @echo "release artifacts in {{ out_dir }}"
    @ls -lh "{{ out_dir }}"

build-archive command goos goarch: _validate-version
    @just _build-archive "{{ command }}" "{{ goos }}" "{{ goarch }}"

release-checksums: _validate-version
    #!/usr/bin/env bash
    set -euo pipefail
    cd "{{ out_dir }}"
    archive_count="$(find . -maxdepth 1 -type f \( -name '*_{{ version }}_*.tar.gz' -o -name '*_{{ version }}_*.zip' \) | wc -l)"
    if [[ "$archive_count" -ne 18 ]]; then
      echo "expected 18 release archives, found ${archive_count}" >&2
      exit 1
    fi
    sha256sum ./*_"{{ version }}"_*.tar.gz ./*_"{{ version }}"_*.zip > checksums.txt

_validate-version:
    @if [[ ! "{{ version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$ ]]; then echo "VERSION must be a semantic version without the leading v: {{ version }}" >&2; exit 64; fi

_build-pingcode goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    name="pingcode-{{ version }}-{{ goos }}-{{ goarch }}"
    echo "building ${name}"
    CGO_ENABLED=0 GOOS="{{ goos }}" GOARCH="{{ goarch }}" \
      go build -trimpath -buildvcs=false \
      -ldflags "-s -w -buildid= -X main.version={{ version }} -X main.commit={{ commit }}" \
      -o "{{ out_dir }}/${name}" ./cmd/pingcode
    (
      cd "{{ out_dir }}"
      sha256sum "${name}" > "${name}.sha256"
    )

_build-fns goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    name="fns-{{ version }}-{{ goos }}-{{ goarch }}"
    echo "building ${name}"
    CGO_ENABLED=0 GOOS="{{ goos }}" GOARCH="{{ goarch }}" \
      go build -trimpath -buildvcs=false \
      -ldflags "-s -w -buildid= -X main.version={{ version }} -X main.commit={{ commit }}" \
      -o "{{ out_dir }}/${name}" ./cmd/fns
    (
      cd "{{ out_dir }}"
      sha256sum "${name}" > "${name}.sha256"
    )

_build-archive command goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    command="{{ command }}"
    goos="{{ goos }}"
    goarch="{{ goarch }}"
    binary="$command"
    archive_base="${command}_{{ version }}_${goos}_${goarch}"
    ldflags="-s -w -buildid="
    mkdir -p "{{ out_dir }}"
    output_dir="$(cd "{{ out_dir }}" && pwd)"

    if [[ "$goos" == "windows" ]]; then
      binary="${binary}.exe"
    fi
    if [[ "$command" == "pingcode" || "$command" == "fns" ]]; then
      ldflags+=" -X main.version={{ version }} -X main.commit={{ commit }}"
    fi

    stage="$(mktemp -d)"
    echo "building ${archive_base}"
    CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" \
      go build -trimpath -buildvcs=false -ldflags "$ldflags" \
      -o "${stage}/${binary}" "./cmd/${command}"

    cp LICENSE THIRD_PARTY_NOTICES.md "$stage/"
    chmod 0755 "${stage}/${binary}"
    chmod 0644 "${stage}/LICENSE" "${stage}/THIRD_PARTY_NOTICES.md"

    if [[ "$goos" == "windows" ]]; then
      (
        cd "$stage"
        zip -q "${output_dir}/${archive_base}.zip" "$binary" LICENSE THIRD_PARTY_NOTICES.md
      )
    else
      tar -C "$stage" -czf "${output_dir}/${archive_base}.tar.gz" \
        "$binary" LICENSE THIRD_PARTY_NOTICES.md
    fi
    rm "${stage}/${binary}"
    rm "${stage}/LICENSE"
    rm "${stage}/THIRD_PARTY_NOTICES.md"
    rmdir "$stage"
