set shell := ["bash", "-eo", "pipefail", "-c"]

version := env_var_or_default("VERSION", "0.1.0")
commit := env_var_or_default("COMMIT", `git rev-parse --short=12 HEAD 2>/dev/null || echo unknown`)
out_dir := env_var_or_default("OUT_DIR", "dist")
mcp2cli_version := "0.1.10"

default:
    @just --list

verify:
    #!/usr/bin/env bash
    set -euo pipefail
    umask 0022
    go mod verify
    go test ./...
    go test -race ./...
    go vet ./...

# Download the current official PingCode API description and prove that the
# loader can convert the complete corpus.
pingcode-spec-check:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    spec_file="$(mktemp "$(cd "{{ out_dir }}" && pwd)/pingcode-api-data.XXXXXX.json")"
    trap 'rm "$spec_file"' EXIT
    curl --fail --silent --show-error --location \
      https://open.pingcode.com/api_data.json \
      --output "$spec_file"
    PINGCODE_API_DATA_FILE="$spec_file" \
      go test -run TestOfficialAPIDocFile -v ./internal/pingcodert

# Download the pinned default FNS Swagger description and prove conversion,
# filtering, and Restish command generation against it.
fns-spec-check:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    spec_file="$(mktemp "$(cd "{{ out_dir }}" && pwd)/fns-swagger.XXXXXX.yaml")"
    trap 'rm "$spec_file"' EXIT
    curl --fail --silent --show-error --location \
      https://raw.githubusercontent.com/haierkeys/fast-note-sync-service/b6b4566352f39e0404530ed1b58248a815a6d763/docs/swagger.yaml \
      --output "$spec_file"
    actual="$(sha256sum "$spec_file" | awk '{print $1}')"
    expect="ae6a880bb9accf472f45d41a922db67617755ce6b7352aef971e7f969ad0d113"
    if [[ "$actual" != "$expect" ]]; then
      echo "pinned FNS swagger SHA256 mismatch: got $actual want $expect" >&2
      exit 1
    fi
    FNS_SPEC_CHECK_FILE="$spec_file" \
      go test -run TestPinnedSpecFile -v ./internal/fnsrt

# Download the pinned complete Ozon Seller OpenAPI snapshot and prove that all
# operations can be repaired and converted into a Restish command tree.
ozon-spec-check:
    #!/usr/bin/env bash
    set -euo pipefail
    spec_file="$(mktemp /tmp/ozon-seller-openapi.XXXXXX.json)"
    trap 'rm "$spec_file"' EXIT
    curl --fail --silent --show-error --location \
      https://raw.githubusercontent.com/PCDCK/ozon-mcp/7e1bea2dd7510064311f1d357d014bb012a18847/src/ozon_mcp/data/seller_swagger.json \
      --output "$spec_file"
    actual="$(sha256sum "$spec_file" | awk '{print $1}')"
    expect="c54962e9481ac776e14c0fe4f987e0ff74fde68a793e6b640f70db6cdaabdba5"
    if [[ "$actual" != "$expect" ]]; then
      echo "pinned Ozon OpenAPI SHA256 mismatch: got $actual want $expect" >&2
      exit 1
    fi
    OZON_SPEC_CHECK_FILE="$spec_file" \
      go test -count=1 -run TestFullSellerSpecCorpus -v ./internal/ozonrt

# Refresh and verify third-party compliance evidence for release binaries.
compliance-check:
    #!/usr/bin/env bash
    set -euo pipefail
    umask 0022
    {
      echo "# Linked module closure for release binaries"
      echo "# Generated by: just compliance-check"
      echo "# Scope: union of go list -deps for ./cmd/aicli ./cmd/pingcode ./cmd/fns ./cmd/ozon ./cmd/lanhu"
      echo
      for pkg in ./cmd/aicli ./cmd/pingcode ./cmd/fns ./cmd/ozon ./cmd/lanhu; do
        echo "## $pkg"
        go list -deps -json "$pkg" | jq -r 'select((.Standard|not) and .Module != null and (.Module.Main|not)) | [.Module.Path, .Module.Version] | @tsv' | sort -u
        echo
      done
      echo "## union"
      for pkg in ./cmd/aicli ./cmd/pingcode ./cmd/fns ./cmd/ozon ./cmd/lanhu; do
        go list -deps -json "$pkg" | jq -r 'select((.Standard|not) and .Module != null and (.Module.Main|not)) | [.Module.Path, .Module.Version] | @tsv'
      done | sort -u
    } > openwiki/compliance/modules-linked.txt
    go mod verify | tee openwiki/compliance/go-mod-verify.txt
    go tool govulncheck -json ./... > openwiki/compliance/govulncheck.json
    # Human-readable evidence copy; gate decides pass/fail from JSON.
    go tool govulncheck ./... > openwiki/compliance/govulncheck.txt 2>&1 || true
    go run ./internal/compliance/gate \
      -findings openwiki/compliance/govulncheck.json \
      -allowlist openwiki/compliance/govulncheck-allowlist.md

test:
    go test ./...

test-fns:
    go test ./internal/swagger2rt ./internal/fnsrt ./cmd/fns

test-ozon:
    go test ./internal/ozonrt ./cmd/ozon

test-lanhu:
    go test ./internal/lanhurt ./cmd/lanhu

test-devopsh:
    go test ./internal/devopshrt ./cmd/devopsh

build-fns: _validate-version
    @just _build-fns linux amd64
    @just _build-fns linux arm64

verify-fns: test-fns
    @just build-fns

build-pingcode: _validate-version
    @just _build-pingcode linux amd64
    @just _build-pingcode linux arm64

build-ozon: _validate-version
    @just _build-ozon linux amd64
    @just _build-ozon linux arm64

build-lanhu: _validate-version
    @just _build-lanhu linux amd64
    @just _build-lanhu linux arm64

build: build-pingcode build-fns build-ozon build-lanhu

release-build: _validate-version
    @just build-archive aicli linux amd64
    @just build-archive aicli linux arm64
    @just build-archive aicli darwin amd64
    @just build-archive aicli darwin arm64
    @just build-archive aicli windows amd64
    @just build-archive aicli windows arm64
    @just build-archive pingcode linux amd64
    @just build-archive pingcode linux arm64
    @just build-archive pingcode darwin amd64
    @just build-archive pingcode darwin arm64
    @just build-archive pingcode windows amd64
    @just build-archive pingcode windows arm64
    @just build-archive fns linux amd64
    @just build-archive fns linux arm64
    @just build-archive fns darwin amd64
    @just build-archive fns darwin arm64
    @just build-archive fns windows amd64
    @just build-archive fns windows arm64
    @just build-archive ozon linux amd64
    @just build-archive ozon linux arm64
    @just build-archive ozon darwin amd64
    @just build-archive ozon darwin arm64
    @just build-archive ozon windows amd64
    @just build-archive ozon windows arm64
    @just build-archive lanhu linux amd64
    @just build-archive lanhu linux arm64
    @just build-archive lanhu darwin amd64
    @just build-archive lanhu darwin arm64
    @just build-archive lanhu windows amd64
    @just build-archive lanhu windows arm64
    @just build-archive devopsh linux amd64
    @just build-archive devopsh linux arm64
    @just build-archive devopsh darwin amd64
    @just build-archive devopsh darwin arm64
    @just release-checksums
    @echo "release artifacts in {{ out_dir }}"
    @ls -lh "{{ out_dir }}"

build-archive command goos goarch: _validate-version
    @just _build-archive "{{ command }}" "{{ goos }}" "{{ goarch }}"

release-checksums: _validate-version
    #!/usr/bin/env bash
    set -euo pipefail
    cd "{{ out_dir }}"
    archive_count="$(find . -maxdepth 1 -type f \( -name '*_{{ version }}_*.tar.gz' -o -name '*_{{ version }}_*.zip' \) | wc -l)"
    if [[ "$archive_count" -ne 34 ]]; then
      echo "expected 34 release archives, found ${archive_count}" >&2
      exit 1
    fi
    sha256sum ./*_"{{ version }}"_*.tar.gz ./*_"{{ version }}"_*.zip > checksums.txt

_validate-version:
    @if [[ ! "{{ version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$ ]]; then echo "VERSION must be a semantic version without the leading v: {{ version }}" >&2; exit 64; fi

_build-pingcode goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    name="pingcode-{{ version }}-{{ goos }}-{{ goarch }}"
    echo "building ${name}"
    CGO_ENABLED=0 GOOS="{{ goos }}" GOARCH="{{ goarch }}" \
      go build -trimpath -buildvcs=false \
      -ldflags "-s -w -buildid= -X main.version={{ version }} -X main.commit={{ commit }}" \
      -o "{{ out_dir }}/${name}" ./cmd/pingcode
    (
      cd "{{ out_dir }}"
      sha256sum "${name}" > "${name}.sha256"
    )

_build-fns goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    name="fns-{{ version }}-{{ goos }}-{{ goarch }}"
    echo "building ${name}"
    CGO_ENABLED=0 GOOS="{{ goos }}" GOARCH="{{ goarch }}" \
      go build -trimpath -buildvcs=false \
      -ldflags "-s -w -buildid= -X main.version={{ version }} -X main.commit={{ commit }}" \
      -o "{{ out_dir }}/${name}" ./cmd/fns
    (
      cd "{{ out_dir }}"
      sha256sum "${name}" > "${name}.sha256"
    )

_build-ozon goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    name="ozon-{{ version }}-{{ goos }}-{{ goarch }}"
    echo "building ${name}"
    CGO_ENABLED=0 GOOS="{{ goos }}" GOARCH="{{ goarch }}" \
      go build -trimpath -buildvcs=false \
      -ldflags "-s -w -buildid= -X main.version={{ version }} -X main.commit={{ commit }}" \
      -o "{{ out_dir }}/${name}" ./cmd/ozon
    (
      cd "{{ out_dir }}"
      sha256sum "${name}" > "${name}.sha256"
    )

_build-lanhu goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ out_dir }}"
    name="lanhu-{{ version }}-{{ goos }}-{{ goarch }}"
    echo "building ${name}"
    CGO_ENABLED=0 GOOS="{{ goos }}" GOARCH="{{ goarch }}" \
      go build -trimpath -buildvcs=false \
      -ldflags "-s -w -buildid= -X main.version={{ version }} -X main.commit={{ commit }}" \
      -o "{{ out_dir }}/${name}" ./cmd/lanhu
    (
      cd "{{ out_dir }}"
      sha256sum "${name}" > "${name}.sha256"
    )

_build-archive command goos goarch:
    #!/usr/bin/env bash
    set -euo pipefail
    command="{{ command }}"
    goos="{{ goos }}"
    goarch="{{ goarch }}"
    binary="$command"
    archive_base="${command}_{{ version }}_${goos}_${goarch}"
    ldflags="-s -w -buildid="
    mkdir -p "{{ out_dir }}"
    output_dir="$(cd "{{ out_dir }}" && pwd)"

    if [[ "$goos" == "windows" ]]; then
      binary="${binary}.exe"
    fi
    if [[ "$command" == "pingcode" || "$command" == "fns" || "$command" == "ozon" || "$command" == "lanhu" ]]; then
      ldflags+=" -X main.version={{ version }} -X main.commit={{ commit }}"
    fi

    stage="$(mktemp -d)"
    echo "building ${archive_base}"
    CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" \
      go build -trimpath -buildvcs=false -ldflags "$ldflags" \
      -o "${stage}/${binary}" "./cmd/${command}"

    if [[ "$command" == "devopsh" ]]; then
      case "${goos}/${goarch}" in
        linux/amd64) target=x86_64-unknown-linux-musl; expected=a0e53b0685638b0263415fa891d5884f52419b24579dc513fd2db1c11327735e ;;
        linux/arm64) target=aarch64-unknown-linux-musl; expected=0fd984d7398d1d6db8b583d63a33dbdfaab3c928c59848299addfdfd50121b6c ;;
        darwin/amd64) target=x86_64-apple-darwin; expected=57df130f2b09762690bb856364cde61bb93ec512b46a2c0147b0527d7675833c ;;
        darwin/arm64) target=aarch64-apple-darwin; expected=f292de88842ef767f71b967d13276cd083ca3a70a08af1a9870ee102dca3792d ;;
        *) echo "mcp2cli {{ mcp2cli_version }} is unavailable for ${goos}/${goarch}" >&2; exit 64 ;;
      esac
      runtime_archive="${stage}/mcp2cli.tar.xz"
      curl --fail --silent --show-error --location \
        "https://github.com/mcp2cli/source-code/releases/download/v{{ mcp2cli_version }}/mcp2cli-{{ mcp2cli_version }}-${target}.tar.xz" \
        --output "$runtime_archive"
      printf '%s  %s\n' "$expected" "$runtime_archive" | sha256sum -c -
      tar -xJf "$runtime_archive" -C "$stage" --strip-components=1 \
        "mcp2cli-{{ mcp2cli_version }}-${target}/mcp2cli" \
        "mcp2cli-{{ mcp2cli_version }}-${target}/LICENSE"
      mv "${stage}/LICENSE" "${stage}/MCP2CLI_LICENSE"
      rm "$runtime_archive"
    fi

    cp LICENSE THIRD_PARTY_NOTICES.md "$stage/"
    chmod 0755 "${stage}/${binary}"
    chmod 0644 "${stage}/LICENSE" "${stage}/THIRD_PARTY_NOTICES.md"

    if [[ "$goos" == "windows" ]]; then
      (
        cd "$stage"
        zip -q "${output_dir}/${archive_base}.zip" "$binary" LICENSE THIRD_PARTY_NOTICES.md
      )
    else
      files=("$binary" LICENSE THIRD_PARTY_NOTICES.md)
      if [[ "$command" == "devopsh" ]]; then files+=(mcp2cli MCP2CLI_LICENSE); fi
      tar -C "$stage" -czf "${output_dir}/${archive_base}.tar.gz" "${files[@]}"
    fi
    rm "${stage}/${binary}"
    rm "${stage}/LICENSE"
    rm "${stage}/THIRD_PARTY_NOTICES.md"
    if [[ "$command" == "devopsh" ]]; then
      rm "${stage}/mcp2cli"
      rm "${stage}/MCP2CLI_LICENSE"
    fi
    rmdir "$stage"
